// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVn54-Fo4qiVIR03cTL7nwoKHV52YXS4w',
    appId: '1:456288482132:web:4975dc1d715b29dcf50ec1',
    messagingSenderId: '456288482132',
    projectId: 'danleo',
    authDomain: 'danleo.firebaseapp.com',
    storageBucket: 'danleo.firebasestorage.app',
    measurementId: 'G-15RST9B6RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqo7QzbY4XxVeCMP8HWFAEIkxoPw9HxE',
    appId: '1:456288482132:android:5bbdbb6ca14b120ef50ec1',
    messagingSenderId: '456288482132',
    projectId: 'danleo',
    storageBucket: 'danleo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJw71bqTVloU8ISyeYZw8njiVGN0tpJY',
    appId: '1:456288482132:ios:899f42b28520dc5bf50ec1',
    messagingSenderId: '456288482132',
    projectId: 'danleo',
    storageBucket: 'danleo.firebasestorage.app',
    iosBundleId: 'com.example.danleo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmJw71bqTVloU8ISyeYZw8njiVGN0tpJY',
    appId: '1:456288482132:ios:899f42b28520dc5bf50ec1',
    messagingSenderId: '456288482132',
    projectId: 'danleo',
    storageBucket: 'danleo.firebasestorage.app',
    iosBundleId: 'com.example.danleo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVn54-Fo4qiVIR03cTL7nwoKHV52YXS4w',
    appId: '1:456288482132:web:1061bf7a2c94ccd0f50ec1',
    messagingSenderId: '456288482132',
    projectId: 'danleo',
    authDomain: 'danleo.firebaseapp.com',
    storageBucket: 'danleo.firebasestorage.app',
    measurementId: 'G-C3KZRKCFB3',
  );
}
