final List<Map<String, dynamic>> productos = [
  {
    "name": "Vaqueros de mezclilla",
    "precio": 60,
    "descripcion": "Estilo vintage lavado azul para nina",
    "urlImage": "https://i.postimg.cc/PfSQvYRT/nina-1-jean.webp",
  },
  {
    "name": "Sudadera Comoda",
    "precio": 40,
    "descripcion": "Manga Larga con Estampado de Estrellas",
    "urlImage": "https://i.postimg.cc/SNj76RB8/nina-2-sudadera.webp",
  },
  {
    "name": "Vestido Elegante",
    "precio": 50,
    "descripcion": "Manga Larga con Contraste y Blanco",
    "urlImage": "https://i.postimg.cc/L5QkdF1n/nina-3-vestido.webp",
  },
  {
    "name": "Jersey de Punto con Cuello",
    "precio": 41,
    "descripcion": "Moda Juvenil Dulce y Tierno para Primavera Otono",
    "urlImage": "https://i.postimg.cc/FRD3cXGD/nina-4-chompa.webp",
  },
  {
    "name": "Conjunto de Tres Piezas",
    "precio": 65,
    "descripcion": "Moda Primavera y Otono Blusa Blanca de Manga Larga con Cuello Redondo",
    "urlImage": "https://i.postimg.cc/2ySdXS3s/nina-5-conjunto.webp",
  },
  {
    "name": "Sudadera de chica",
    "precio": 38,
    "descripcion": "Estampado geometrico de gato",
    "urlImage": "https://i.postimg.cc/KYt51WdH/nina-6-sudadera.webp",
  },
  {
    "name": "Camisa de algodon preppy",
    "precio": 39,
    "descripcion": "Manga corta de verano con lazo removible",
    "urlImage": "https://i.postimg.cc/tT5t5xRd/nina-7-camisa.webp",
  },
  {
    "name": "2 piezas de tops",
    "precio": 26,
    "descripcion": "Graficos de aranas para ninas",
    "urlImage": "https://i.postimg.cc/7ZFVY4Qz/nina-8-top.webp",
  },
  {
    "name": "Camiseta de manga corta",
    "precio": 23,
    "descripcion": "Estampado de gato platano de moda y mono",
    "urlImage": "https://i.postimg.cc/63wfn0K5/nina-9-camiseta.webp",
  },
  {
    "name": "Vaqueros de mezclilla",
    "precio": 60,
    "descripcion": "Estilo vintage lavado azul para nina",
    "urlImage": "https://i.postimg.cc/XYGLbqx3/nina-10-chaqueta.webp",
  },
  {
    "name": "Sudadera Casual Capucha",
    "precio": 37.90,
    "descripcion": "Composicion 95 Poliester 5 Elastano Material Poliester Estilo de cuello Capucha",
    "urlImage": "https://i.postimg.cc/Jh0hPTd1/Sudadera-Casual-Capucha.jpg",
  },
  {
    "name": "Chaqueta calida polar",
    "precio": 74.47,
    "descripcion": "Estilo de cuello Cuello de cardigan Temporada Invierno Instrucciones de cuidado Lavar a maquina o limpieza en seco profesional Estilo Casual",
    "urlImage": "https://i.postimg.cc/VkLskGwj/Chaqueta-calida-polar.jpg",
  },
  {
    "name": "Camiseta negra",
    "precio": 19.78,
    "descripcion": "Ropa de nino de entre 3 anos a 5 anos",
    "urlImage": "https://i.postimg.cc/sDzDtf0H/Camiseta-negra.jpg",
  },
  {
    "name": "Ropa casual nino",
    "precio": 47.18,
    "descripcion": "Ropa negra Estilo casual De 12 anos a 9 anos",
    "urlImage": "",
  },
  {
    "name": "Pantalon Vaguero para ninos",
    "precio": 68.90,
    "descripcion": "Jean para ninos Suelto y comodo casual y estilo urbano para salir 45 Algodon 55 Poliester",
    "urlImage": "https://i.postimg.cc/JzPn3wx6/Pantalon-Vaguero-para-ni-os.jpg",
  },
  {
    "name": "Conjunto Sudadera pantalon ninos",
    "precio": 83.99,
    "descripcion": "Conjunto casual de ropa de ninos Lavar maquina 100 Poliester",
    "urlImage": "https://i.postimg.cc/X7g73MRj/Conjunto-Sudadera-pantalon-ni-os.jpg",
  },
  {
    "name": "Traje de Beisbol piezas para otono invierno",
    "precio": 55.50,
    "descripcion": "Conjunto de traje de beisbol para nino Estampado predisenado",
    "urlImage": "https://i.postimg.cc/2jhScLTB/Traje-de-Beisbol-piezas-para-oto-o-invierno.jpg",
  },
  {
    "name": "Paquete 3 sudaderas capucha",
    "precio": 83.90,
    "descripcion": "Paquete de 3 sudaderas Conjunto de ropa de ninos 100 Poliester Para ninos de 12 anos a menos",
    "urlImage": "https://i.postimg.cc/0N4y3pL7/Paquete-3-sudaderas-capucha.jpg",
  },
  {
    "name": "Traje Casual ninos",
    "precio": 78.90,
    "descripcion": "Traje casual de ninos 100 Poliester Refrescante ideal para la primavera u otono",
    "urlImage": "https://i.postimg.cc/HnwWVFjt/Traje-Casual-ni-os.jpg",
  },
  {
    "name": "Sudadera Capucha CR7",
    "precio": 38.90,
    "descripcion": "Sudadera con capucha de CR7 3D Ideal para salir en primavera u otono",
    "urlImage": "https://i.postimg.cc/MTjp8nSN/Sudarea-Capucha-CR7.jpg",
  },
  {
    "name": "Sudadera Astronauta",
    "precio": 35.90,
    "descripcion": "Sudadera astronauta ligera Ideal para primavera u otono Para 12 anos o menos 95 Poliester",
    "urlImage": "https://i.postimg.cc/d3PtQJQ1/Sudadera-Astronauta.jpg",
  },
  {
    "name": "Blusa Oxford",
    "precio": 89.90,
    "descripcion": "Blusa Oxford clasica ideal para un look formal Con botones al frente y cuello rigido Colores disponibles Celeste blanco rosado",
    "urlImage": "https://i.postimg.cc/SKKm8rfc/blusa.png",
  },
  {
    "name": "Blusa de vestir",
    "precio": 84.90,
    "descripcion": "Blusa entallada de manga larga con corte elegante y femenino perfecta para oficina Colores disponibles Azul claro blanco negro",
    "urlImage": "https://i.postimg.cc/bNQYjdvS/blusa-oxford.png",
  },
  {
    "name": "Camiseta del Peru",
    "precio": 79.90,
    "descripcion": "Camiseta sin mangas con diseno oficial de la seleccion peruana estilo deportivo Colores disponibles Blanco con franja roja",
    "urlImage": "https://i.postimg.cc/k5hqybTz/camiseta-del-per.png",
  },
  {
    "name": "Casaca con diseno",
    "precio": 149.90,
    "descripcion": "Casaca acolchada con diseno de estampado moderno capucha y cierre completo Colores disponibles Azul con diseno multicolor",
    "urlImage": "https://i.postimg.cc/W4KcZP3P/casaca-con-dise-o.png",
  },
  {
    "name": "Casaca de cuero",
    "precio": 199.90,
    "descripcion": "Casaca corta de cuero sintetico con estilo urbano y elegante Colores disponibles Negro marron",
    "urlImage": "https://i.postimg.cc/Xq6M2cdH/casaca-de-cuero.png",
  },
  {
    "name": "Casaca deportiva",
    "precio": 239.90,
    "descripcion": "Casaca tecnica de alto rendimiento para actividades como ciclismo o motociclismo Colores disponibles Negro con detalles grises",
    "urlImage": "https://i.postimg.cc/Y2FM1jYD/casaca-deportiva.png",
  },
  {
    "name": "Casaca felpuda",
    "precio": 169.90,
    "descripcion": "Casaca acolchada y abrigadora con forro interior tipo polar y capucha Colores disponibles Azul electrico gris rojo",
    "urlImage": "https://i.postimg.cc/zBgZSPbH/casaca-felpuda.png",
  },
  {
    "name": "Casaca simple",
    "precio": 129.90,
    "descripcion": "Casaca ligera e impermeable perfecta para dias lluviosos o clima fresco Colores disponibles Coral celeste verde menta",
    "urlImage": "https://i.postimg.cc/1RGbmFpS/casaca-simple.png",
  },
  {
    "name": "Pantalon de escalada",
    "precio": 109.90,
    "descripcion": "Pantalon outdoor con multiples bolsillos ideal para trekking o actividades al aire libre Colores disponibles Turquesa gris oscuro negro",
    "urlImage": "https://i.postimg.cc/28wpwW6G/pantalon-escalada.png",
  },
  {
    "name": "Pantalon negro",
    "precio": 89.90,
    "descripcion": "Jogger deportivo con pretina alta comodo y versatil para uso casual o entrenamiento Colores disponibles Negro gris beige",
    "urlImage": "https://i.postimg.cc/zBW6Rb6n/pantal-n-negro.png",
  },
  {
    "name": "Polo deportivo",
    "precio": 74.90,
    "descripcion": "Polo tecnico con tecnologia de secado rapido ideal para actividades fisicas Colores disponibles Azul con degradado fucsia negro",
    "urlImage": "https://i.postimg.cc/cCSj71GP/polo-deportivo.png",
  },
  {
    "name": "Chaqueta Elson OBM",
    "precio": 150,
    "descripcion": "Una pieza calida para invierno",
    "urlImage": "https://i.postimg.cc/qBLCVVJ8/Chaqueta-ropa-antifrio-fotor-bg-remover-2025051721446.png",
  },
  {
    "name": "Camisa holgada a cuadros",
    "precio": 100,
    "descripcion": "Holgada y casual con botones",
    "urlImage": "https://i.postimg.cc/25hV0g9L/Camisa-hombre-cuadros-fotor-bg-remover-2025051721341.png",
  },
  {
    "name": "Camisa de punto",
    "precio": 90,
    "descripcion": "Camisa minimalista de manga larga",
    "urlImage": "https://i.postimg.cc/wvk3pLp6/Camisa-de-puntos-fotor-bg-remover-2025051721330.png",
  },
  {
    "name": "Chaqueta forro polar",
    "precio": 118,
    "descripcion": "Con capucha y multiples cremalleras",
    "urlImage": "https://i.postimg.cc/rFZ0s1ts/Chaqueta-forro-polar-fotor-bg-remover-2025051721436.png",
  },
  {
    "name": "Pantalones tacticos",
    "precio": 105,
    "descripcion": "Ideal para trabajo al aire libre",
    "urlImage": "https://i.postimg.cc/bJf28qSR/Pantalones-tacticos-fotor-bg-remover-2025051721538.png",
  },
  {
    "name": "Camiseta Henley",
    "precio": 100,
    "descripcion": "De cuello alto con contraste de color",
    "urlImage": "https://i.postimg.cc/Vk3JBzgc/Camiseta-henley-fotor-bg-remover-2025051721417.png",
  },
  {
    "name": "Sudadera forrada de Vellon",
    "precio": 116,
    "descripcion": "Cuello alto y cremallera media",
    "urlImage": "https://i.postimg.cc/nr0sv7Rd/Sudadera-vellon-fotor-bg-remover-2025051721514.png",
  },
  {
    "name": "Sueter casual",
    "precio": 116,
    "descripcion": "Tejido suave y cierre frontal",
    "urlImage": "https://i.postimg.cc/vTQggXzg/Sueter-casual-otonio-fotor-bg-remover-2025051721526.png",
  },
  {
    "name": "Sudadera vintage",
    "precio": 80,
    "descripcion": "Jersey de invierno calido",
    "urlImage": "https://i.postimg.cc/xdzbWX8C/Sudadera-hombre-vintage-fotor-bg-remover-202505172164.png",
  },
  {
    "name": "Sudadera deportiva",
    "precio": 150,
    "descripcion": "Con multiples bolsillos y cuello redondo",
    "urlImage": "https://i.postimg.cc/wv5RjnhY/Sudadera-deportiva-fotor-bg-remover-2025051721548.png",
  },
  {
    "name": "Camiseta estilo gofre",
    "precio": 110,
    "descripcion": "Apariencia falsa de 2 piezas con cuello V",
    "urlImage": "https://i.postimg.cc/wvz3ZFnf/Camiseta-estilo-gofre-fotor-bg-remover-202505172144.png",
  },
  {
    "name": "Jean de ajuste delgado",
    "precio": 120,
    "descripcion": "Denim elastico de estilo urbano",
    "urlImage": "https://i.postimg.cc/fRF92cwp/Jean-cargo-ajuste-delgado-fotor-bg-remover-2025051721310.png",
  },
  {
    "name": "Pantalon de cargo",
    "precio": 150,
    "descripcion": "Con multiples bolsillos y de ajuste casual",
    "urlImage": "https://i.postimg.cc/0j2j2jk7/Pantalones-cargo-negro-fotor-bg-remover-2025051721320.png",
  },
  {
    "name": "Chaqueta casual estilo motocicleta",
    "precio": 215,
    "descripcion": "Ajuste regular con cierre de cremallera",
    "urlImage": "https://i.postimg.cc/SxXXMnWr/Chaqueta-estilo-motociclista-fotor-bg-remover-2025051721426.png",
  },
  {
    "name": "Chaqueta vaquera ajustada",
    "precio": 150,
    "descripcion": "Estilo casual y lavable a maquina",
    "urlImage": "https://i.postimg.cc/TY35T71B/Chaqueta-vaqueta-ajustada-fotor-bg-remover-2025051721456.png",
  },
];